spring:
  application:
    name: test
  data:
    redis:
      host: localhost
      port: 6379

coolsms:
  apikey: NCS6FSXZJNQ2W4VB
  apisecret: PW7L7IUM5REUVNL0HYKANDIL7XSLBRHK
  fromnumber: 01026270378
